### ISSUE TITLE
Mac OS Error

### ISSUE THREAD

**Issue by SonyPan82** [just-harry/tiny-ui-fix-for-ts3#1] opened 2023-12-26 21:55 UTC
Thank you very much for your work. I'm looking forward to trying it; however, an error appears after selecting and generating on the browser interface

Line |
1705 |  …             $Result = [TinyUIFixForTS3Patcher.LayoutScaler]::ScaleLay …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "ScaleLayoutBy" with "3" argument(s): "The input string '6.000122'
     | was not in a correct format."

**Comment by just-harry** [comment] 2023-12-28 00:51
Sorry for the delay in responding to you, on this. Thank you for the bug-report.

I think the cause of this is an XML layout having a decimal value where the layout-scaler is expecting an integer value, or something along those lines.

I've released version 1.0.4, which includes more graceful error handling for this, so it should just skip the layout causing the error, and will print which package has the layout. \
Feel free to reply to this ticket with the resource-key and the name of the package of the layout that's failing: I can take a look and see whether the layout or the layout-scaler is at fault.

**Comment by just-harry** [comment] 2023-12-28 17:05
Okay, I think this is actually fixed in version 1.0.5, which I've just released.

**Comment by SonyPan82** [comment] 2023-12-29 09:34
Perfect! Thank you very much. It was really a long-awaited feature on Mac! It now works on Apple Silicon MacBook with Sonoma !

**Comment by just-harry** [comment] 2023-12-29 15:19
Thank you, I'm glad to hear it

**Closed as completed by just-harry** 2023-12-29 15:19 UTC
